@ChatWSAppAPI_HostAddress = http://localhost:5140

###
GET {{ChatWSAppAPI_HostAddress}}/allmessages/
Accept: application/json
###
GET {{ChatWSAppAPI_HostAddress}}/user?user=a
Accept: application/json
###
GET {{ChatWSAppAPI_HostAddress}}/group?groupname=qwertz&key=qwertz
Accept: application/json
###
GET {{ChatWSAppAPI_HostAddress}}/word?word=yo
Accept: application/json
###
GET {{ChatWSAppAPI_HostAddress}}/all/?Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEyMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJqb2huX2RvZSIsImV4cCI6MTcwNTc4NDY4OSwiaXNzIjoiaXNzdWVyIiwiYXVkIjoiYXVkaWVuY2UifQ.ibggad8XRQUlcnaDc0WceppzqDMD4ZNBd-lMHIF1qto
Accept: application/json